package fc.is.modelo;
// Generated 20/02/2018 02:36:48 PM by Hibernate Tools 4.3.1



/**
 * ExperiencialaboralId generated by hbm2java
 */
public class ExperiencialaboralId  implements java.io.Serializable {


     private int idprofesionista;
     private int idempresa;

    public ExperiencialaboralId() {
    }

    public ExperiencialaboralId(int idprofesionista, int idempresa) {
       this.idprofesionista = idprofesionista;
       this.idempresa = idempresa;
    }
   
    public int getIdprofesionista() {
        return this.idprofesionista;
    }
    
    public void setIdprofesionista(int idprofesionista) {
        this.idprofesionista = idprofesionista;
    }
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExperiencialaboralId) ) return false;
		 ExperiencialaboralId castOther = ( ExperiencialaboralId ) other; 
         
		 return (this.getIdprofesionista()==castOther.getIdprofesionista())
 && (this.getIdempresa()==castOther.getIdempresa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdprofesionista();
         result = 37 * result + this.getIdempresa();
         return result;
   }   


}


