package fc.is.modelo;
// Generated 20/02/2018 02:36:48 PM by Hibernate Tools 4.3.1



/**
 * Formacionacademica generated by hbm2java
 */
public class Formacionacademica  implements java.io.Serializable {


     private FormacionacademicaId id;
     private Profesionista profesionista;

    public Formacionacademica() {
    }

    public Formacionacademica(FormacionacademicaId id, Profesionista profesionista) {
       this.id = id;
       this.profesionista = profesionista;
    }
   
    public FormacionacademicaId getId() {
        return this.id;
    }
    
    public void setId(FormacionacademicaId id) {
        this.id = id;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }




}


