package fc.is.modelo;
// Generated 20/02/2018 02:36:48 PM by Hibernate Tools 4.3.1



/**
 * FormacionacademicaId generated by hbm2java
 */
public class FormacionacademicaId  implements java.io.Serializable {


     private int idprofesionista;
     private String colegio;
     private char grado;
     private String periodo;

    public FormacionacademicaId() {
    }

    public FormacionacademicaId(int idprofesionista, String colegio, char grado, String periodo) {
       this.idprofesionista = idprofesionista;
       this.colegio = colegio;
       this.grado = grado;
       this.periodo = periodo;
    }
   
    public int getIdprofesionista() {
        return this.idprofesionista;
    }
    
    public void setIdprofesionista(int idprofesionista) {
        this.idprofesionista = idprofesionista;
    }
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }
    public char getGrado() {
        return this.grado;
    }
    
    public void setGrado(char grado) {
        this.grado = grado;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormacionacademicaId) ) return false;
		 FormacionacademicaId castOther = ( FormacionacademicaId ) other; 
         
		 return (this.getIdprofesionista()==castOther.getIdprofesionista())
 && ( (this.getColegio()==castOther.getColegio()) || ( this.getColegio()!=null && castOther.getColegio()!=null && this.getColegio().equals(castOther.getColegio()) ) )
 && (this.getGrado()==castOther.getGrado())
 && ( (this.getPeriodo()==castOther.getPeriodo()) || ( this.getPeriodo()!=null && castOther.getPeriodo()!=null && this.getPeriodo().equals(castOther.getPeriodo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdprofesionista();
         result = 37 * result + ( getColegio() == null ? 0 : this.getColegio().hashCode() );
         result = 37 * result + this.getGrado();
         result = 37 * result + ( getPeriodo() == null ? 0 : this.getPeriodo().hashCode() );
         return result;
   }   


}


